

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/layout/Navbar";
import { AuthProvider } from '@/lib/auth/AuthContext';
import { SessionWarning } from '@/components/auth/SessionWarning';
import { SessionExpiredModal } from '@/components/auth/SessionExpiredModal';

import { ReactQueryProvider } from '@/lib/ReactQueryProvider';
import { ScrollToTop } from '@/components/ui/ScrollToTop'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <head>
  <link rel="manifest" href="/manifest.json" />
  <meta name="theme-color" content="#3b82f6" />
  <meta name="mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="default" />
  <meta name="apple-mobile-web-app-title" content="ADD Management" />
  <link rel="apple-touch-icon" href="/icon-192.png" />
</head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <ReactQueryProvider>
          <AuthProvider>
            <Navbar />
            {children}
            <ScrollToTop />
            <SessionWarning />
            <SessionExpiredModal />
          </AuthProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
